### ISSUE TITLE
Add v0.1.0 tag

### ISSUE THREAD

**Issue by marbre** [iml130/pfdl-vscode-extension#7]
The *Release Notes* section in the README mention a [v0.1.0](https://github.com/iml130/pfdl-vscode-extension/blob/main/README.md#v010) release, thus the appropriate version (initial release?) should be tagged accordingly.

**Comment by OliverStolzBO** [comment]
Tag was created [here](https://github.com/iml130/pfdl-vscode-extension/tree/v0.1.0)
